### PR TITLE
Fix postgres support

### LINKED ISSUE #1: Test with PostgreSQL

### PR DESCRIPTION
**Pull request by jplitza**
Fixes #1

### CODE REVIEW

File: lib/Db/IndexDocumentMapper.php [hunk 1]
```diff
@@ -53,31 +53,43 @@ public function search(ISearchRequest $request, string $providerId, IDocumentAcc
...
-				break;
-			case IDBConnection::PLATFORM_SQLITE:
-				break;
-			case IDBConnection::PLATFORM_ORACLE:
+				$qb
+					->andWhere(
+						$qb->expr()->orX(
+							$qb->expr()->eq('owner', $viewerId),
+							"access_users @> $jsonViewerId::jsonb",
+							"access_groups ?| JSON_QUERY($jsonGroups, '$' RETURNING text[])",
```
Comment (jplitza) [inline lib/Db/IndexDocumentMapper.php:86]: This does not actually work, because Doctrine swallows the `?`, assuming it indicates a positional parameter to the prepared statement. No idea yet how to resolve that...
